package com.velopayments.blockchain.crypt;

import com.velopayments.blockchain.init.Initializer;

public class SigningPublicKey {

    /**
     * Create a public signing key from a raw byte array.
     *
     * @param rawBytes The raw bytes of the public key.
     */
    public SigningPublicKey(byte[] rawBytes) {
        this.rawBytes = rawBytes;
    }

    /**
     * Get the raw bytes of a public signing key.
     */
    public byte[] getRawBytes() {
        return rawBytes;
    }

    /**
     * Verify the signature of a message generated by the private half of this
     * key.
     *
     * @param signature The signature to verify.
     * @param message The message to verify.
     *
     * @return true if the signature is valid and false otherwise.
     */
    public boolean verify(Signature signature, Message message) {
        return verifyNative(Initializer.getInstance(), signature, message);
    }

    private native boolean verifyNative(
        long nativeInst, Signature signature, Message message);

    private byte[] rawBytes;
}
